// <auto-generated/>
#pragma warning disable CS0618
using BangumiApi.V0.Characters;
using BangumiApi.V0.Episodes;
using BangumiApi.V0.Indices;
using BangumiApi.V0.Me;
using BangumiApi.V0.Persons;
using BangumiApi.V0.Revisions;
using BangumiApi.V0.Search;
using BangumiApi.V0.Subjects;
using BangumiApi.V0.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BangumiApi.V0
{
    /// <summary>
    /// Builds and executes requests for operations under \v0
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V0RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The characters property</summary>
        public global::BangumiApi.V0.Characters.CharactersRequestBuilder Characters
        {
            get => new global::BangumiApi.V0.Characters.CharactersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The episodes property</summary>
        public global::BangumiApi.V0.Episodes.EpisodesRequestBuilder Episodes
        {
            get => new global::BangumiApi.V0.Episodes.EpisodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The indices property</summary>
        public global::BangumiApi.V0.Indices.IndicesRequestBuilder Indices
        {
            get => new global::BangumiApi.V0.Indices.IndicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::BangumiApi.V0.Me.MeRequestBuilder Me
        {
            get => new global::BangumiApi.V0.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The persons property</summary>
        public global::BangumiApi.V0.Persons.PersonsRequestBuilder Persons
        {
            get => new global::BangumiApi.V0.Persons.PersonsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The revisions property</summary>
        public global::BangumiApi.V0.Revisions.RevisionsRequestBuilder Revisions
        {
            get => new global::BangumiApi.V0.Revisions.RevisionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::BangumiApi.V0.Search.SearchRequestBuilder Search
        {
            get => new global::BangumiApi.V0.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subjects property</summary>
        public global::BangumiApi.V0.Subjects.SubjectsRequestBuilder Subjects
        {
            get => new global::BangumiApi.V0.Subjects.SubjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::BangumiApi.V0.Users.UsersRequestBuilder Users
        {
            get => new global::BangumiApi.V0.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiApi.V0.V0RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V0RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BangumiApi.V0.V0RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V0RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v0", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
